#!/bin/bash

row=0
col=0
size=5
c=0

while [[ $col -lt $size ]]; do
	
	while [[ $row -lt $size ]]; do
    
        while [[ $c != $col ]]; do
            echo -n " "
            let c=c+1
        done
    	
	echo -n "*"
	let row++
	        
    done
	
echo ""
let row=0
let col++
c=0
done
