#!/bin/bash

row=0
col=0
size=5

while [[ $col -lt $size ]]; do

    while [[ $row -lt $size ]] ; do   

	if [[ $size-1-$row -gt $col ]]; then
        echo -n " "
    else 
        echo -n "*"
    fi
        let row++
 
    done
    
echo ""

let row=0
let col++


done
